#pragma once

#include "AC_CustomControl_config.h"

#if AP_CUSTOMCONTROL_ADRC_ENABLED

#include <AC_ADRC/arduAttCont.h>

#include "AC_CustomControl_Backend.h"

class AC_CustomControl_ADRC : public AC_CustomControl_Backend {
public:
    AC_CustomControl_ADRC(AC_CustomControl& frontend, AP_AHRS_View*& ahrs, AC_AttitudeControl*& att_control, AP_Motors* motors, float dt);

    Vector3f update(void) override;
    void reset(void) override;

    // user settable parameters
    static const struct AP_Param::GroupInfo var_info[];

protected:
    //从官方姿态控制器状态准备的完整输入接口 仅应替换控制律;目标生成、输入整形和Heli混合功能仍保留在ArduPilot中
    struct ControllerInput {
        float dt_s;

        // 当前和目标姿态 
        Quaternion attitude_body_quat;
        Quaternion attitude_target_raw_quat;
        Quaternion attitude_target_quat;

        // 姿态误差
        Vector3f attitude_error_rad;

        // 姿态误差
        Vector3f attitude_error_control_rad;

        // 目标角速度
        Vector3f target_ang_vel_target_frame_radps;
        Vector3f rate_ff_body_raw_radps;
        Vector3f rate_ff_body_radps;

        // Optional reference: official body-frame rate target already generated by AC_AttitudeControl.
        // A non-PID custom controller does not have to use this; it is exposed for logging, comparison,
        // or controllers that want to track the official shaped rate target.
        Vector3f official_rate_target_body_radps;

        // Latest gyro measurement used as angular-rate feedback. Units: rad/s.
        Vector3f gyro_latest_radps;

        // Useful derived signal for controllers that are written around rate error.
        // With the default interface this is only feed-forward minus measured rate; full rate target
        // generation can be implemented by the user control law from attitude_error_control_rad.
        Vector3f rate_ff_error_radps;

        float thrust_angle_rad;
        float thrust_error_angle_rad;
        float feedforward_scalar;
        float yaw_control_scalar;
        bool body_frame_ff_enabled;

        // Motor saturation flags from AP_Motors/AP_MotorsHeli.  Use these in the custom law for
        // anti-windup, observer freeze/bleed, or adaptive-state management.
        bool motor_roll_limited;
        bool motor_pitch_limited;
        bool motor_yaw_limited;

        // Spool-state flags.  State update and output permission are enforced before motor output,
        // but are also exposed so the user control law can freeze or bleed internal states explicitly.
        AP_Motors::SpoolState spool_state;
        bool ground_or_idle;
        bool spool_transition;
        bool throttle_unlimited;
        bool allow_controller_update;
        bool allow_motor_output;

        // Heli piro-compensation interface.  For controllers with roll/pitch slow states
        // (ESO disturbance estimate, integrator-like state, adaptive term, etc.), rotate those
        // states by piro_cos/piro_sin each update.
        float piro_delta_angle_rad;
        float piro_cos;
        float piro_sin;
    };

        struct ControllerOutput {
        // Normalized mixer inputs expected by AP_Motors/AP_MotorsHeli, not PWM, not torque,
        // not desired angular velocity. Typical range after limiting is [-1, +1].
        Vector3f normalized_rpy;
    };

    bool build_controller_input(ControllerInput& input);
    bool run_user_controller(const ControllerInput& input, ControllerOutput& output);
    Vector3f finalize_output(const ControllerInput& input, const ControllerOutput& output);
    Vector3f zero_output() const;

    void reset_controller_state();
    void reset_for_spool_inhibition();

    bool option_enabled(uint8_t option) const;
    float get_output_limit_rp() const;
    float get_output_limit_yaw() const;
    float get_spool_output_scale() const;
    bool is_spool_state_inhibited(const ControllerInput& input) const;

    // Simulink generated controller object.  The default user-control body below calls this object,
    // but all upstream/downstream interface and safety logic is outside the Simulink model.
    arduAttCont simulink_controller;

    enum ADRCOption : uint8_t {
        // Use body-frame rate feed-forward generated from AC_AttitudeControl target attitude motion.
        OPTION_USE_RATE_FF        = 1U << 0,

        // Attenuate yaw attitude error during large thrust-vector error, matching the official
        // attitude-controller priority: roll/pitch thrust-vector correction before heading correction.
        OPTION_SCALE_YAW_ERROR    = 1U << 1,

        // Allow the controller law to run during SPOOLING_UP/SPOOLING_DOWN.  Output is still multiplied
        // by CC3_SPOOL_SCL.  Leave disabled for fuel helicopters unless the custom controller has
        // explicit low-rotor-speed state handling.
        OPTION_RUN_WHILE_SPOOLING = 1U << 2,
    };
    // Parameters for the ADRC/custom backend interface layer.
    AP_Float _out_max_rp;
    AP_Float _out_max_yaw;
    AP_Float _spool_output_scale;
    AP_Int8  _options;

    // General user parameters passed through to the custom controller body.
    // They are not consumed by the interface layer; use them inside run_user_controller().
    AP_Float _user_param1;
    AP_Float _user_param2;
    AP_Float _user_param3;

    Vector3f _last_raw_out;
    Vector3f _last_limited_out;
    bool _spool_inhibit_reset_done;
    bool _controller_has_run;
};

#endif  // AP_CUSTOMCONTROL_ADRC_ENABLED
